train_config:
  # out_dir: "/mnt/nvme1n1p1/baoyu/logs/rope_0119"
  out_dir: "/mnt/sda/adaptigraph/logs/all_0414"
  phases: ["train", "valid"]
  load_model: False
  model_checkpoint: "/mnt/nvme1n1p1/baoyu/logs/rope_0119/checkpoints/model_100.pth"
  optimizer_checkpoint: "/mnt/nvme1n1p1/baoyu/logs/rope_0119/checkpoints/optim_100.pth"
  device: "cuda:0"
  
  batch_size: 128 #128
  n_epochs: 100 #100
  n_iters_per_epoch:
    train: 1000 #1000
    valid: 100 #100
  log_interval: 50
  random_seed: 42
  n_his: 4
  n_future: 3

model_config:
  verbose: False

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150

  nf_physics_hidden: 20
  nf_physics: 10

  # particle encoder
  attr_dim: 2  # object and end effector
  state_dim: 0  # x, y, z
  offset_dim: 0
  action_dim: 3
  pstep: 3
  sequence_length: 4
  density_dim: 0  # particle density

  # rel encoder
  rel_particle_dim: 0
  rel_attr_dim: 2
  rel_group_dim: 1  # sum of difference of group one-hot vector
  rel_distance_dim: 3
  rel_density_dim: 0

  # phys encoding
  use_vae: False
  phys_encode: False

dataset_config:
  data_dir: "/mnt/sda/data_simple/mixed"
  prep_data_dir: "/mnt/sda/adaptigraph/preprocess_010/mixed_0410"
  datasets:
    ratio: 
        train: [0, 0.9]
        valid: [0.9, 1]
    material:
      rope:
        fps_radius_range: [0.18, 0.22]
        adj_radius_range: [0.48, 0.52]
        state_noise: 
          train: 0.05
          valid: 0.0
        phys_noise: 
          train: 0.0
          valid: 0.0
        max_n: 1
        max_tool: 1
        max_nobj: 100
        max_ntool: 5
        max_nR: 2000
      cloth:
        fps_radius_range: [0.18, 0.22]
        adj_radius_range: [0.48, 0.52]
        state_noise: 
          train: 0.05
          valid: 0.0
        phys_noise: 
          train: 0.0
          valid: 0.0
        max_n: 1
        max_tool: 1
        max_nobj: 100
        max_ntool: 5
        max_nR: 2000
      granular:
        fps_radius_range: [0.18, 0.22]
        adj_radius_range: [0.38, 0.42]
        state_noise: 
          train: 0.04
          valid: 0.0
        phys_noise: 
          train: 0.0
          valid: 0.0
        max_n: 1
        max_tool: 1
        max_nobj: 100
        max_ntool: 5
        max_nR: 2000

material_config:
  material_index:
    rope: 0
    cloth: 1
    granular: 2
  rope:
    physics_params: 
      - name: "stiffness"
        use: True
        min: 0.
        max: 1.
  cloth:
    physics_params: 
      - name: "sf"
        use: True
        min: 0.
        max: 1.
  granular:
    physics_params: 
      - name: "granular_scale"
        use: True
        min: 0.1
        max: 0.3