train_config:
  out_dir: "/mnt/nvme1n1p1/baoyu/logs/box_shape_0125"
  phases: ["train", "valid"]
  load_model: False
  model_checkpoint: "/mnt/nvme1n1p1/baoyu/checkpoints/latest.pth"
  optimizer_checkpoint: "/mnt/nvme1n1p1/baoyu/checkpoints/latest_optim.pth"
  device: "cuda"
  
  batch_size: 128
  n_epochs: 100
  n_iters_per_epoch:
    train: 1000
    valid: 100
  log_interval: 50
  random_seed: 42
  n_his: 4
  n_future: 5

model_config:
  verbose: False

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150

  nf_physics_hidden: 20
  nf_physics: 10

  # particle encoder
  attr_dim: 5  # object and end effector
  state_dim: 0  # x, y, z
  offset_dim: 0
  action_dim: 4  # dx, dy, com_x, com_y
  pstep: 3
  sequence_length: 4
  density_dim: 0  # particle density

  # rel encoder
  rel_particle_dim: 0
  rel_attr_dim: 5
  rel_group_dim: 0  # sum of difference of group one-hot vector
  rel_distance_dim: 2
  rel_density_dim: 0

  # canonical
  # rel_can_attr_dim: 0
  # rel_canonical_distance_dim: 0
  # rel_canonical_attr_dim: 0
  # rel_canonical_thresh: 0

  # phys encoding
  use_vae: False
  phys_encode: False

dataset_config:
  datasets:
    - name: "rigid"
      materials: ["rigid"]
      data_dir: "/mnt/nvme1n1p1/baoyu/data/box_shape"
      prep_data_dir: "/mnt/nvme1n1p1/baoyu/preprocess_010_fu5/box_shape"
      fps_radius_range: [0,0] #TODO: not used
      adj_radius_range: [0,0] #TODO: not used
      state_noise: 
        train: 0.0 # +-0.02rad # TODO: 4 4mm
        valid: 0.0
      phys_noise: 
        train: 0.0
        valid: 0.0
      ratio: 
        train: [0, 0.9]
        valid: [0.9, 1]
      max_n: 1
      max_tool: 1
      max_nobj: 4
      max_ntool: 1
      max_nR: 50

material_config:
  material_index:
    rigid: 0
  rigid:
    physics_params: 
      - name: "com_x"
        use: True
        min: 0.0
        max: 2.0
      - name: "com_y"
        use: True
        min: 0.0
        max: 2.0
