train_config:
  out_dir: "logs/rope_40"
  # out_dir: "/mnt/nvme1n1p1/baoyu/logs/rope_0119"
  phases: ["train", "valid"]
  load_model: False
  device: "cuda:0"
  
  batch_size: 128
  n_epochs: 100
  n_iters_per_epoch:
    train: 1000
    valid: 100
  log_interval: 50
  random_seed: 42
  n_his: 4
  n_future: 3

model_config:
  verbose: False

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150
  out_dim: 3

  nf_physics_hidden: 20
  nf_physics: 10

  # particle encoder
  attr_dim: 2  # object and end effector
  state_dim: 0  # x, y, z
  offset_dim: 0
  action_dim: 3
  pstep: 3
  sequence_length: 4
  density_dim: 0  # particle density

  # rel encoder
  rel_particle_dim: 0
  rel_attr_dim: 2
  rel_group_dim: 1  # sum of difference of group one-hot vector
  rel_distance_dim: 3
  rel_density_dim: 0

  # canonical
  # rel_can_attr_dim: 0
  # rel_canonical_distance_dim: 0
  # rel_canonical_attr_dim: 0
  # rel_canonical_thresh: 0

  # phys encoding
  use_vae: False
  phys_encode: False

dataset_config:
  materials: ["rope"]
  # data_dir: "/mnt/sda/data/rope"
  # prep_data_dir: "/mnt/sda/preprocess/rope"
  data_dir: "../data/rope_40"
  prep_data_dir: "../data/preprocess/rope_40"
  fps_radius_range: [0.18, 0.22]
  # fps_radius_range: [0.23, 0.27]
  # fps_radius_range: [0.28, 0.32]
  # adj_radius_range: [0.48, 0.52]
  adj_radius_range: [0.58, 0.62]
  # adj_radius_range: [0.68, 0.72]
  # adj_radius_range: [0.78, 0.82]
  state_noise: 
    train: 0.05
    valid: 0.0
  phys_noise: 
    train: 0.0
    valid: 0.0
  ratio: 
    train: [0, 0.9]
    valid: [0.9, 1]
  max_n: 1
  max_tool: 1
  max_nobj: 100
  max_ntool: 1
  max_nR: 2000

material_config:
  material_index:
    rope: 0
  rope:
    physics_params: 
      - name: "particle_radius"
        use: False
        min: 0.
        max: 1.
      - name: "num_particles"
        use: False
        min: 0.
        max: 5000.
      - name: "length"
        use: False
        min: 2.5
        max: 5.0
      - name: "thickness"
        use: False
        min: 2.5
        max: 4.0
      - name: "dynamic_friction"
        use: False
        min: 0.1
        max: 0.45
      - name: "stiffness"
        use: True
        min: 0.
        max: 1.